name: webdriverio-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.16.0
        - name: Install
          run: npm install
        - name: Test
          run: npm run browserstack
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs